### ISSUE TITLE
Ensure builds work on Linux

### ISSUE THREAD

**Issue by adamfowleruk** [adamfowleruk/groundupdb#21]
**Please start with a use case description for a USER of this work**
[Who] As a developer
[What] I need to work on GroundUpDB across multiple platforms, including Linux
[Value] In order to add cool functionality to GroundUpDB, and use GroundUpDB on Linux

**Describe the solution you'd like**
Ensure CMake works as expected with all tests on Linux

**Describe alternatives you've considered**
N/A

**Additional context**
Work already completed for Mac 64 bit (CLang) and Windows 10 64 bit (MSVCC via CMake)

Also ensure PR from others works as expected.

**Comment by adamfowleruk** [comment]
@phlash - Please verify that stem (which incorporates your PR plus a change for Windows) works on your machines.

**Comment by phlash** [comment]
@adamfowleruk all good here on Debian stable.
```
===============================================================================
All tests passed (325 assertions in 9 test cases)
```
