### ISSUE TITLE
Add CMake support

### ISSUE THREAD

**Issue by adamfowleruk** [adamfowleruk/groundupdb#9]
[Who]   As a user
[What]  I would like to build the project with CMake
[Value] To reduce the number of extra dev tools I need to use GroundUpDB

For @battleguard

**Comment by phlash** [comment]
Sorry Adam - opening this one again as it does not build 'out of the box' for me on Debian buster (stable), fixes underway :)

**Comment by adamfowleruk** [comment]
All done. Please test again. See #21 and #27

**Comment by phlash** [comment]
Confirmed - ok, see #21
